name: Terraform Tests

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:

  terraform-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init Compute
        run: terraform init
        working-directory: modules/compute

      - name: Terraform Test Compute
        run: terraform test
        working-directory: modules/compute